spring.application.name=task-service
spring.datasource.url=jdbc:postgresql://localhost:5433/task-service
spring.datasource.username=postgres
spring.datasource.password=postgres@123
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
task.processing.max-concurrent-tasks=3
task.processing.polling-delay-ms=2000
task.recovery.processing-timeout-seconds=60
task.recovery.fixed-delay-ms=30000