CREATE TABLE IF NOT EXISTS tasks (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    file VARCHAR(255) NOT NULL UNIQUE,
                                    status VARCHAR(255) NOT NULL,
                                    created_at TIMESTAMP NOT NULL,
                                    result TEXT,
                                    error_message TEXT
);